### ISSUE TITLE
Ajouter les matchs des phases finales

### ISSUE THREAD

**Issue by Ivanovtch** [mbernardeau/euro-2021#23]
Nous avons ajouté tous les matchs des poules, il manque seulement les matchs des phases finales. On peux maintenant les rajouter sans mettre d'équipes avec le display="false".

**Comment by naustra** [comment]
Adapter le modèle de proximité des scores pour la phase finale dans le même temps

**Comment by naustra** [comment]
écrire le squelette dans le json avec le display à "false"

Vérifier que sur un export vers firebase, on ne part pas les scores des anciens matchs joués.

**Comment by naustra** [comment]
Sera fait au fur et à mesure. Pas besoin de le décrire dans une tache
