### ISSUE TITLE
Mettre en place sauvegarde automatique pour ne pas perdre de données

### ISSUE THREAD

**Issue by naustra** [mbernardeau/euro-2021#74]
Que se passe t-il si une erreur de calcul fait inscrire NaN dans la base ou écrit une valeur erronée ?

Vaut-il mieux tester à fond l'algo de calcul ou prévoir des sauvegardes de base temporaire au cas où il y ait un soucis ponctuellement ?

**Comment by mbernardeau** [comment]
Faut prévoir les deux.

Pour la sauvegarde auto on peut le faire assez facilement avec https://firebase.google.com/docs/firestore/solutions/schedule-export. Mais attention aux coûts en lecture et en stockage.
